# Generated by Django 5.2 on 2026-07-22 09:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import utils.thumbnails
import utils.validators
import wilayah_indonesia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayah_indonesia', '0006_wilayahidmapping_nama_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KebunDeforestationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whisp_analysis', models.JSONField(blank=True, help_text='Hasil analisis WHISP untuk geometri kebun', null=True)),
                ('whisp_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', help_text='Status analisis WHISP', max_length=20)),
                ('whisp_job_id', models.CharField(blank=True, help_text='ID job RQ untuk tracking', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_legalitas', models.FileField(blank=True, null=True, upload_to='legalitas/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_legalitas', models.ImageField(blank=True, null=True, upload_to='thumbs/legalitas/')),
                ('file_stdb', models.FileField(blank=True, null=True, upload_to='stdb/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_stdb', models.ImageField(blank=True, null=True, upload_to='thumbs/stdb/')),
                ('file_rspo', models.FileField(blank=True, null=True, upload_to='rspo/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_rspo', models.ImageField(blank=True, null=True, upload_to='thumbs/rspo/')),
                ('file_ispo', models.FileField(blank=True, null=True, upload_to='ispo/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_ispo', models.ImageField(blank=True, null=True, upload_to='thumbs/ispo/')),
                ('file_gambar_peta', models.FileField(blank=True, null=True, upload_to='gambar_peta/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_gambar_peta', models.ImageField(blank=True, null=True, upload_to='thumbs/gambar_peta/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(utils.thumbnails.ThumbnailsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Kebun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kebun', models.CharField(db_index=True, max_length=100, unique=True)),
                ('id_perbaikan', models.CharField(blank=True, help_text='ID Perbaikan dari Lembaga', max_length=100, null=True)),
                ('lokasi_kebun', models.CharField(help_text='Nama lokasi atau daerah kebun', max_length=100)),
                ('luas', models.DecimalField(decimal_places=2, default=0.0, help_text='Luas (Ha)', max_digits=10)),
                ('luas_peta', models.DecimalField(decimal_places=2, default=0.0, help_text='Luas (Ha)', max_digits=10)),
                ('waktu_tanam', models.DateField(blank=True, help_text='Bulan dan Tahun', null=True)),
                ('jumlah_pokok', models.IntegerField()),
                ('is_rspo', models.BooleanField(default=False, help_text='Sudah RSPO')),
                ('is_ispo', models.BooleanField(default=False, help_text='Sudah ISPO')),
                ('jenis_legalitas', models.CharField(blank=True, choices=[('1', 'Sertifikat Hak Milik (SHM)'), ('2', 'Girik/SKT/SKGR/Hak Pengelolaan'), ('3', 'Tanah ulayat/adat'), ('4', 'Lahan Kawasan Hutan Produksi/Sosial'), ('5', 'Lahan Kawasan Hutan Produksi/Konservasi'), ('7', 'Surat Pernyataan (SP)'), ('8', 'Surat Jaminan Bank (SJB)'), ('9', 'Surat Pernyataan Tanah (SPT)')], max_length=2, null=True)),
                ('nomor_legalitas', models.CharField(blank=True, max_length=50, null=True)),
                ('pemilik_legalitas', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_bibit', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_stdb', models.CharField(blank=True, max_length=100, null=True)),
                ('titik_koordinat', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Koordinat kebun', null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Peta Kebun', null=True, srid=4326)),
                ('komoditas', models.CharField(blank=True, choices=[('14', 'CENGKEH'), ('15', 'COKLAT/KAKAO'), ('41', 'KARET'), ('52', 'KELAPA'), ('53', 'KELAPA SAWIT'), ('69', 'KOPI'), ('121', 'TEBU'), ('122', 'TEH'), ('124', 'TEMBAKAU'), ('86', 'PALA'), ('0', 'SEMUA'), ('99', 'LAINNYA')], max_length=50, null=True)),
                ('pola_tanam', models.CharField(blank=True, choices=[('1', 'Monokultur'), ('2', 'Polikultur')], max_length=50, null=True)),
                ('jenis_lahan', models.CharField(blank=True, choices=[('1', 'Lahan Mineral'), ('2', 'Lahan Basa (Pasang Surut, Gambut)')], max_length=50, null=True)),
                ('asal_benih', models.CharField(blank=True, choices=[('1', 'Produsen Benih Bersertifikat'), ('2', 'Produsen Benih Tidak Bersertifikat'), ('3', 'Tidak Tahu')], max_length=50, null=True)),
                ('jenis_pupuk', models.CharField(blank=True, choices=[('1', 'Organik'), ('2', 'Anorganik'), ('3', 'Kombinasi')], max_length=50, null=True)),
                ('tahun_peremajaan', models.IntegerField(blank=True, help_text='Tahun peremajaan terakhir', null=True)),
                ('jumlah_pohon', models.IntegerField(blank=True, help_text='Jumlah pohon di kebun', null=True)),
                ('total_prod_per_tahun', models.DecimalField(blank=True, decimal_places=2, help_text='Total produksi per tahun dalam (kg)', max_digits=15, null=True)),
                ('mitra_penjualan', models.CharField(blank=True, help_text='Mitra penjualan hasil panen', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.desa')),
                ('kabupaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.kabupaten')),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.kecamatan')),
            ],
            bases=(wilayah_indonesia.models.WilayahDisplayMixin, models.Model),
        ),
    ]
