# Generated by Django 5.2 on 2026-07-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kebun', '0001_initial'),
        ('petani', '0001_initial'),
        ('wilayah_indonesia', '0006_wilayahidmapping_nama_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebun',
            name='petani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petani.petani'),
        ),
        migrations.AddField(
            model_name='kebun',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.provinsi'),
        ),
        migrations.AddField(
            model_name='kebundeforestationanalysis',
            name='kebun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_analysis', to='kebun.kebun'),
        ),
        migrations.AddField(
            model_name='lampiran',
            name='kebun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kebun.kebun'),
        ),
    ]
