# Generated by Django 5.2 on 2026-07-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanPetani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kebutuhan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Petani',
                'verbose_name_plural': 'Laporan Petani',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaporanStatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('tahun', models.PositiveSmallIntegerField()),
                ('judul', models.CharField(max_length=255)),
                ('kebutuhan', models.TextField()),
                ('file_excel', models.FileField(blank=True, null=True, upload_to='laporan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Statistik',
                'verbose_name_plural': 'Laporan Statistik',
                'ordering': ['-tahun', '-bulan'],
            },
        ),
        migrations.CreateModel(
            name='LaporanSTDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sudah_terbit', 'Sudah Terbit'), ('belum_terbit', 'Belum Terbit'), ('dalam_proses', 'Dalam Proses')], max_length=20)),
                ('judul', models.CharField(max_length=255)),
                ('kebutuhan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan STDB',
                'verbose_name_plural': 'Laporan STDB',
                'ordering': ['-created_at'],
            },
        ),
    ]
