# Generated by Django 5.2 on 2026-07-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laporan', '0001_initial'),
        ('petani', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laporanpetani',
            name='petani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='petani.petani'),
        ),
        migrations.AddField(
            model_name='laporanstatistik',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_statistik_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
