# Generated by Django 5.2 on 2026-07-22 09:04

import utils.thumbnails
import utils.validators
import wilayah_indonesia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angkutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penjualan', models.DateField(help_text='Tanggal penjualan TBS')),
                ('driver', models.CharField(help_text='Nama driver angkutan', max_length=100)),
                ('no_registrasi', models.CharField(help_text='Nomor registrasi angkutan', max_length=50, unique=True)),
                ('no_polisi', models.CharField(help_text='Nomor polisi kendaraan', max_length=20)),
                ('jumlah_tandan', models.IntegerField(default=0, help_text='Jumlah tandan TBS')),
                ('berat_timbangan', models.DecimalField(decimal_places=2, default=0, help_text='Berat timbangan dalam Kg', max_digits=10)),
                ('tarra', models.DecimalField(decimal_places=2, default=0, help_text='Berat tarra dalam Kg', max_digits=10)),
                ('t_potongan_persen', models.DecimalField(decimal_places=2, default=0, help_text='Persentase potongan tarra (%)', max_digits=5)),
                ('t_potongan_kg', models.DecimalField(decimal_places=2, default=0, help_text='Potongan tarra dalam Kg', max_digits=10)),
                ('berat_bersih', models.DecimalField(decimal_places=2, default=0, help_text='Berat bersih TBS dalam Kg', max_digits=10)),
                ('harga_per_kilo', models.DecimalField(decimal_places=2, default=0, help_text='Harga per kilogram dalam Rupiah', max_digits=10)),
                ('total_penjualan', models.DecimalField(decimal_places=2, default=0, help_text='Total penjualan dalam Rupiah', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Angkutan',
                'verbose_name_plural': 'Angkutan',
                'ordering': ['-tanggal_penjualan', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KelompokPenyetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(db_index=True, help_text='Nama Kelompok Tani', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kelompok Penyetor',
                'verbose_name_plural': 'Kelompok Penyetor',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='penjualan/file_1/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_1', models.ImageField(blank=True, null=True, upload_to='thumbs/penjualan/file_1/')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='penjualan/file_2/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_2', models.ImageField(blank=True, null=True, upload_to='thumbs/penjualan/file_2/')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='penjualan/file_3/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_3', models.ImageField(blank=True, null=True, upload_to='thumbs/penjualan/file_3/')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='penjualan/file_4/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_4', models.ImageField(blank=True, null=True, upload_to='thumbs/penjualan/file_4/')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='penjualan/file_5/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_5', models.ImageField(blank=True, null=True, upload_to='thumbs/penjualan/file_5/')),
                ('file_6', models.FileField(blank=True, null=True, upload_to='penjualan/file_6/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_6', models.ImageField(blank=True, null=True, upload_to='thumbs/penjualan/file_6/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lampiran Penjualan',
                'verbose_name_plural': 'Lampiran Penjualan',
            },
            bases=(utils.thumbnails.ThumbnailsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Pabrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, help_text='Nama Pabrik Tujuan Penjualan', max_length=200)),
                ('alamat', models.TextField(blank=True, help_text='Alamat lengkap pabrik', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pabrik',
                'verbose_name_plural': 'Pabrik',
                'ordering': ['nama'],
            },
            bases=(wilayah_indonesia.models.WilayahDisplayMixin, models.Model),
        ),
    ]
