# Generated by Django 5.2 on 2026-07-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penjualan', '0001_initial'),
        ('petani', '0001_initial'),
        ('wilayah_indonesia', '0006_wilayahidmapping_nama_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelompokpenyetor',
            name='anggota_petani',
            field=models.ManyToManyField(help_text='Petarni yang menyetor', to='petani.petani'),
        ),
        migrations.AddField(
            model_name='kelompokpenyetor',
            name='angkutan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penjualan.angkutan'),
        ),
        migrations.AddField(
            model_name='lampiran',
            name='angkutan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran_penjualan', to='penjualan.angkutan'),
        ),
        migrations.AddField(
            model_name='pabrik',
            name='kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.kabupaten'),
        ),
        migrations.AddField(
            model_name='pabrik',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.kecamatan'),
        ),
        migrations.AddField(
            model_name='pabrik',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.provinsi'),
        ),
        migrations.AddField(
            model_name='angkutan',
            name='pabrik',
            field=models.ForeignKey(blank=True, help_text='Pabrik tujuan penjualan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angkutan_penjualan', to='penjualan.pabrik'),
        ),
        migrations.AddIndex(
            model_name='angkutan',
            index=models.Index(fields=['tanggal_penjualan'], name='penjualan_a_tanggal_1d1a28_idx'),
        ),
        migrations.AddIndex(
            model_name='angkutan',
            index=models.Index(fields=['no_registrasi'], name='penjualan_a_no_regi_e22848_idx'),
        ),
        migrations.AddIndex(
            model_name='angkutan',
            index=models.Index(fields=['driver'], name='penjualan_a_driver_b3854d_idx'),
        ),
    ]
