# Generated by Django 5.2 on 2026-07-22 09:04

import django.db.models.deletion
import utils.fields
import utils.thumbnails
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayah_indonesia', '0006_wilayahidmapping_nama_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_petani', models.CharField(db_index=True, max_length=50, unique=True)),
                ('id_perbaikan', models.CharField(blank=True, help_text='ID Perbaikan dari Lembaga terkait', max_length=100, null=True)),
                ('nama', models.CharField(max_length=100)),
                ('nama_kelompok', models.CharField(db_index=True, max_length=100)),
                ('jns_kelamin', models.CharField(choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], max_length=10)),
                ('no_ktp', models.CharField(db_index=True, max_length=30)),
                ('tempat', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_kk', models.CharField(blank=True, max_length=20, null=True)),
                ('status_perkawinan', models.CharField(blank=True, choices=[('1', 'Belum Kawin'), ('2', 'Kawin'), ('3', 'Cerai Hidup'), ('4', 'Cerai Mati')], max_length=2, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, choices=[('1', 'Tidak punya ijazah SD'), ('2', 'SD/Sederajat'), ('3', 'SMP/Sederajat'), ('4', 'SMA/Sederajat'), ('5', 'SMK'), ('6', 'D1/D2'), ('7', 'D3/Sarjana muda'), ('8', 'D4/S1'), ('9', 'S2/S3'), ('99', 'Lainnya')], max_length=100, null=True)),
                ('no_nib', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_terbit_sppl', models.DateField(blank=True, null=True)),
                ('no_wa', models.CharField(blank=True, max_length=20, null=True, validators=[utils.validators.validate_indonesian_phone_number])),
                ('keanggotaan', models.CharField(choices=[('1', 'Aktif'), ('0', 'Tidak Aktif'), ('2', 'Belum Anggota')], default='1', help_text='Status keanggotaan petani', max_length=1)),
                ('tanggal_bergabung', models.DateField(blank=True, help_text='Tanggal petani bergabung ke kelompok', null=True)),
                ('tanggal_keluar', models.DateField(blank=True, help_text='Tanggal petani keluar dari kelompok', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.desa')),
                ('kabupaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.kabupaten')),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.kecamatan')),
                ('provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah_indonesia.provinsi')),
            ],
        ),
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jns_kelamin', models.CharField(blank=True, choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], max_length=10, null=True)),
                ('kelompok_tani', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_ktp', models.CharField(blank=True, max_length=20, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('no_kk', models.CharField(blank=True, max_length=20, null=True)),
                ('no_wa', models.CharField(blank=True, max_length=20, null=True, validators=[utils.validators.validate_indonesian_phone_number])),
                ('status_pekerja', models.CharField(blank=True, choices=[('1', 'Pemilik'), ('2', 'Keluarga'), ('3', 'Buruh Tetap'), ('4', 'Buruh Harian Lepas')], max_length=20, null=True)),
                ('jenis_pekerjaan', utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('1', 'Panen'), ('2', 'Pupuk'), ('3', 'Semprot'), ('4', 'Tebas'), ('5', 'Supir'), ('6', 'Langsir')], max_length=2), blank=True, default=list, size=None)),
                ('jenis_apd', utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('1', 'Apron'), ('2', 'Kaca Mata'), ('3', 'Sepatu'), ('4', 'Helem'), ('5', 'Masker'), ('6', 'Sarung Tangan'), ('7', 'Sarung egrek/dodos')], max_length=2), blank=True, default=list, size=None)),
                ('file_ktp', models.FileField(blank=True, null=True, upload_to='pekerja-ktp/')),
                ('thumb_ktp', models.ImageField(blank=True, null=True, upload_to='thumbs/ktp/')),
                ('file_kk', models.FileField(blank=True, null=True, upload_to='pekerja-kk/')),
                ('thumb_kk', models.ImageField(blank=True, null=True, upload_to='thumbs/kk/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerja', to='petani.petani')),
            ],
            bases=(utils.thumbnails.ThumbnailsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ktp', models.FileField(blank=True, null=True, upload_to='ktp/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_ktp', models.ImageField(blank=True, null=True, upload_to='thumbs/ktp/')),
                ('file_kk', models.FileField(blank=True, null=True, upload_to='kk/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_kk', models.ImageField(blank=True, null=True, upload_to='thumbs/kk/')),
                ('file_nib', models.FileField(blank=True, null=True, upload_to='nib/', validators=[utils.validators.MaxSizeFileValidator(10)])),
                ('thumb_nib', models.ImageField(blank=True, null=True, upload_to='thumbs/nib/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petani.petani')),
            ],
            bases=(utils.thumbnails.ThumbnailsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.BooleanField(default=False, help_text='Sertifikasi Lainnya')),
                ('sl_trainer', models.CharField(blank=True, help_text='Nama trainer Sertifikasi Lainnya', max_length=100, null=True)),
                ('pnc', models.BooleanField(default=False, help_text='RSPO/ISPO')),
                ('pnc_trainer', models.CharField(blank=True, help_text='Nama trainer RSPO/ISPO', max_length=100, null=True)),
                ('k3', models.BooleanField(default=False, help_text='Kesehatan dan Keselamatan Kerja')),
                ('k3_trainer', models.CharField(blank=True, help_text='Nama trainer Kesehatan dan Keselamatan Kerja', max_length=100, null=True)),
                ('sop', models.BooleanField(default=False, help_text='Standar Operasional Prosedur')),
                ('sop_trainer', models.CharField(blank=True, help_text='Nama trainer Standar Operasional Prosedur', max_length=100, null=True)),
                ('fdg', models.BooleanField(default=False, help_text='Pengendalian Diri dan Gizi')),
                ('fdg_trainer', models.CharField(blank=True, help_text='Nama trainer Pengendalian Diri dan Gizi', max_length=100, null=True)),
                ('pestisida', models.BooleanField(default=False, help_text='Penggunaan Pestisida')),
                ('pestisida_trainer', models.CharField(blank=True, help_text='Nama trainer Penggunaan Pestisida', max_length=100, null=True)),
                ('manajemen_api', models.BooleanField(default=False, help_text='Manajemen Api')),
                ('manajemen_api_trainer', models.CharField(blank=True, help_text='Nama trainer Manajemen Api', max_length=100, null=True)),
                ('pengendalian_hpt', models.BooleanField(default=False, help_text='Pengendalian Hama dan Penyakit Tanaman')),
                ('pengendalian_hpt_trainer', models.CharField(blank=True, help_text='Nama trainer Pengendalian Hama dan Penyakit Tanaman', max_length=100, null=True)),
                ('nkt', models.BooleanField(default=False, help_text='Nilai Konservasi Tinggi')),
                ('nkt_trainer', models.CharField(blank=True, help_text='Nama trainer Nilai Konservasi Tinggi', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petani.petani')),
            ],
        ),
    ]
