# Generated by Django 5.2 on 2026-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampiran',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='foto-profile/'),
        ),
        migrations.AddField(
            model_name='lampiran',
            name='thumb_foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/foto-profile/'),
        ),
    ]
