# Generated by Django 5.2 on 2026-02-07 08:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmDesaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('desa', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('properties', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DeforeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label like a identifier (id or something)', max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source_type', models.CharField(choices=[('glad', 'GLAD'), ('radd', 'RADD')], default='glad', max_length=255)),
                ('area_ha', models.FloatField(default=0.0)),
                ('properties', models.JSONField(default=dict)),
                ('date', models.DateField()),
                ('raw_data', models.JSONField(default=dict)),
                ('administrative_area', models.JSONField(default=dict, help_text='Administrative area info like province, regency, district, village')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
