"""
Django settings for safetrace project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import environ
import os
import sentry_sdk
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
env = environ.Env(
    DEBUG = (bool, False),
    DJANGO_ENV =(str, 'local'),
    SECRET_KEY = (str, 'django-insecure-ffy6^oosj-1g&=p&7dsvlwly!qfvym*j4e!n0e7&8b+70dq-xn'),
    STATIC_URL = (str, 'static/'),
    STATIC_ROOT = (str, str(BASE_DIR / 'static')),
    MEDIA_URL = (str, 'media/'),
    MEDIA_ROOT = (str, str(BASE_DIR / 'medias')),
    MEDIA_HOST = (str, 'http://localhost:8000'),
    USE_SENTRY_DNS = (bool, False),
    SENTRY_DNS = (str, 'https://6d23ead7a5cb0531c9217b9ead1c98b9@o4504666402848768.ingest.us.sentry.io/4511015504773120'),
    CACHE_STATIC_LAYER = (int, 60 * 60),
    POPPLER_PATH = (str, '/usr/bin'),
    ALLOWED_HOSTS = (list, ['*']),
    CORS_ALLOW_ALL_ORIGINS = (bool, True),
    CORS_ALLOW_CREDENTIALS = (bool, False),
    CSRF_TRUSTED_ORIGINS = (list, ['http://localhost:4000', 'http://localhost:8000', 'http://127.0.0.1:4000', 
                                   'http://127.0.0.1', 'http://localhost']),
    CORS_ALLOWED_ORIGINS = (list, ['http://localhost:4000', 'http://localhost:8000', 'http://127.0.0.1:4000',
                                   'http://127.0.0.1', 'http://localhost']),
    PROTECTED_MEDIA_USE_XACCEL = (bool, False),
    PROTECTED_MEDIA_XACCEL_PREFIX = (str, '/protected'),
    DEFAULT_RECIPIENTS_ALERT = (list, ['admin@example.com']),
    GEE_SERVICE_ACCOUNT_EMAIL = (str, 'pprp-gee@buatin-160113.iam.gserviceaccount.com'),
    GEE_SERVICE_ACCOUNT_KEY_PATH = (str, str(BASE_DIR / 'gee_service_account_buatin.json')),
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

DJANGO_ENV = env('DJANGO_ENV')
# SECRET_KEY = 'django-insecure-(c_614xvq5ei6wf-6yg7lot*032o^pmca(ku+4f#v0lg0n#u!#'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

GEE_SERVICE_ACCOUNT_EMAIL = env('GEE_SERVICE_ACCOUNT_EMAIL')
GEE_SERVICE_ACCOUNT_KEY_PATH = env('GEE_SERVICE_ACCOUNT_KEY_PATH')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    
    'accounts',
    'kebun',
    'petani',
    'referensi',
    'gap',
    'penjualan',
    'layer_static',
    'alerts',
    'dash_statistics',
    'laporan',
    
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework_gis',
    'post_office',
    'corsheaders',
    'wilayah_indonesia',
    'django_select2',
    'adminsortable2',
    'tinymce',
    'django_rq',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.middlewares.MediaURLMiddleware',  # Custom middleware to handle HTTPS media URL
]

# Security Settings for HTTPS behind proxy/load balancer
# This tells Django to trust the X-Forwarded-Proto header from the proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'safetrace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safetrace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env('DB_NAME'),
        "USER": env('DB_USER'),
        "PASSWORD": env('DB_PASSWORD'),
        "HOST": env('DB_HOST'),
        "PORT": env('DB_PORT'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = env('STATIC_URL')
STATIC_ROOT = env('STATIC_ROOT')
STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

# MEDIA
MEDIA_URL = env('MEDIA_URL')
MEDIA_ROOT = env('MEDIA_ROOT')
MEDIA_HOST = env('MEDIA_HOST')
MEDIA_FORCE_HTTPS = env.bool('MEDIA_FORCE_HTTPS', default=False)

# PROTECTED MEDIA SETTINGS
# Set True in production to use X-Accel-Redirect (Nginx)
# This will make Nginx serve the files, not Django (faster)
PROTECTED_MEDIA_USE_XACCEL = env.bool('PROTECTED_MEDIA_USE_XACCEL', default=False)

# Prefix for X-Accel-Redirect in Nginx config
# Example Nginx config:
#   location /protected {
#       internal;
#       alias /path/to/media/;
#   }
PROTECTED_MEDIA_XACCEL_PREFIX = env('PROTECTED_MEDIA_XACCEL_PREFIX', default='/protected')
ENABLE_SIGNED_MEDIA_URLS = env.bool('ENABLE_SIGNED_MEDIA_URLS', default=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Rest Framework Config
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'utils.PaginationDefault',
    'PAGE_SIZE': 50,
}

# JWT Config
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True
}

AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'utils.auth_backend.UsernameOrEmailBackend',
]

# Email
EMAIL_NOTIF_ON = env.bool('EMAIL_NOTIF_ON', default=True)
EMAIL_BACKEND = 'post_office.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='')
DEFAULT_RECIPIENTS_ALERT = env.list('DEFAULT_RECIPIENTS_ALERT')

APPEND_SLASH=True

POPPLER_PATH = env('POPPLER_PATH')

if env.bool('USE_SENTRY_DNS'):
    sentry_sdk.init(
        dsn=env('SENTRY_DNS'),
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
    )

CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS')
CORS_ALLOW_CREDENTIALS = env.bool('CORS_ALLOW_CREDENTIALS')
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

# Redis Configuration
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')

# Django RQ Configuration
RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': env('REDIS_PASSWORD', default=''),
        'DEFAULT_TIMEOUT': 3600,  # 1 hour timeout
    },
    'whisp': {  # Dedicated queue for WHISP tasks
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 1,
        'PASSWORD': env('REDIS_PASSWORD', default=''),
        'DEFAULT_TIMEOUT': 7200,  # 2 hour timeout for complex analysis
    }
}

# WHISP Configuration
WHISP_QUEUE = 'whisp'
WHISP_API_URL = env('WHISP_API_URL', default='https://whisp.openforis.org/api')
WHISP_API_KEY = env('WHISP_API_KEY', default='xxxx')

# Cache for Static Layer
CACHE_STATIC_LAYER = env('CACHE_STATIC_LAYER')

# Default settings for wilayah indonesia package
WILAYAH_ADM_ID = {
    'prov_kalbar': 61,
    'kab_sekadau': 6109,
    'kab_sanggau': 6103,
    'kab_sintang': 6105,
}
