# Generated by Django 5.2 on 2026-07-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gap', '0001_initial'),
        ('kebun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lb3',
            name='kebun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kebun.kebun'),
        ),
        migrations.AddField(
            model_name='penggunaanpestisida',
            name='kebun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggunaan_pestisida', to='kebun.kebun'),
        ),
        migrations.AddField(
            model_name='penggunaanpupuk',
            name='kebun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggunaan_pupuk', to='kebun.kebun'),
        ),
        migrations.AddField(
            model_name='produksi',
            name='kebun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kebun.kebun'),
        ),
        migrations.AddField(
            model_name='pupuk',
            name='kebun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kebun.kebun'),
        ),
        migrations.AddIndex(
            model_name='penggunaanpestisida',
            index=models.Index(fields=['kebun', 'tahun'], name='gap_penggun_kebun_i_00084c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='penggunaanpestisida',
            unique_together={('kebun', 'tahun')},
        ),
        migrations.AddIndex(
            model_name='penggunaanpupuk',
            index=models.Index(fields=['kebun', 'tahun'], name='gap_penggun_kebun_i_cab2c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='penggunaanpupuk',
            unique_together={('kebun', 'tahun')},
        ),
    ]
